In [1]:
import numpy as np

In [2]:
first_array = np.array(100) # 0-D array
print(first_array)

100


In [4]:
array_1d = np.array([1, 2, 3, 4, 5]) # 1-D array
print(array_1d)

[1 2 3 4 5]


In [5]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D array
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3-D array
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
#print dimension of every array
print(first_array.ndim)
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

0
1
2
3


In [8]:
#Higher Dimensional Arrays
array_5d = np.array([1, 2, 3, 4], ndmin=5)
print(array_5d)

[[[[[1 2 3 4]]]]]


In [11]:
#different methods to create arrays
#empty method
array_empty = np.empty((2, 3)) # 2x3 empty array
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#zero method
array_zeros = np.zeros((2, 3)) # 2x3 array with zeros
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#create an eye matrix(an eye matrix is a square matrix with 1's on the main diagonal)
array_eye = np.eye(3) # 3x3 identity matrix
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#create an ones matrix(ones matrix is a matrix where all the values are 1)
array_ones = np.ones((2, 3)) # 2x3 array with ones
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#create an array with arrange method between 1 and 2 by step 0.05
array_arrange = np.arange(1,2,0.05)
print(array_arrange)

[1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65
 1.7  1.75 1.8  1.85 1.9  1.95]


In [16]:
#an array with linspace method(linspace is used to create an array with a specified number of elements, and within a specified range)
array_linspace = np.linspace(1, 2, 10) # 10 elements between 1 and 2
print(array_linspace)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [19]:
#Meshgrid method(creates a rectangular grid out of an array of x values and an array of y values)
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

#creates a grid of x and y values
X, Y = np.meshgrid(x, y)

print(X)
print("\n")
print(Y)

[[-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 ...
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]]


[[-5.        -5.        -5.        ... -5.        -5.        -5.       ]
 [-4.8989899 -4.8989899 -4.8989899 ... -4.8989899 -4.8989899 -4.8989899]
 [-4.7979798 -4.7979798 -4.7979798 ... -4.7979798 -4.7979798 -4.7979798]
 ...
 [ 4.7979798  4.7979798  4.7979798 ...  4.7979798  4.7979798  4.7979798]
 [ 4.8989899  4.8989899  4.8989899 ...  4.8989899  4.8989899  4.8989899]
 [ 5.         5.         5.        ...  5.         5.         5.       ]]


In [20]:
#create a diagonal matrix(diagonal matrix is a square matrix that has values only in the main diagonal)
array_diag = np.diag([1, 2, 3, 4]) # diagonal matrix
print(array_diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
#create a diagonal matrix with offset(diagonal matrix with offset is a square matrix that has values only in the main diagonal and offset)
array_diag_offset = np.diag([1, 2, 3, 4], k=1) # diagonal matrix with offset
print(array_diag_offset)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [22]:
#create a random matrix
array_random = np.random.rand(2, 3) # 2x3 random matrix
print(array_random)

[[0.659832   0.38448408 0.45932392]
 [0.10665453 0.73941345 0.75761944]]


In [23]:
#create a random matrix with normal distribution(mean=0, std=1)(a normal distribution is a distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean)
array_random_normal = np.random.randn(2, 3) # 2x3 random matrix with normal distribution
print(array_random_normal)

[[ 0.31423825 -1.16831745 -0.58530079]
 [ 1.81750213  0.80054459 -0.00566925]]


In [24]:
#create a random matrix with integers
array_random_int = np.random.randint(1, 10, (2, 3)) # 2x3 random matrix with integers between 1 and 10
print(array_random_int)

[[3 7 7]
 [2 9 3]]


In [25]:
#converting a list into an array
list_exp  = [1,2,4,8,16]
np_arr = np.array(list_exp)

print(np_arr)
print(type(np_arr))

[ 1  2  4  8 16]
<class 'numpy.ndarray'>


In [26]:
#converting a tuple into an array
tuple_exp = (1,2,4,8,16)
np_arr = np.array(tuple_exp)

print(np_arr)
print(type(np_arr))

[ 1  2  4  8 16]
<class 'numpy.ndarray'>


In [28]:
#copying an array
array_copy = np.copy(array_2d) # copy array_2d
print(array_copy)

#show memory location of each array
print(id(array_2d))
print(id(array_copy))

[[1 2 3]
 [4 5 6]]
1250205327600
1250225787984


In [30]:
#copying an array with view method(view method is used to create a new array object that looks at the same data)
array_view = array_2d.view() # view array_2d
print(array_view)

#show memory location of each array
print(id(array_2d))
print(id(array_view))

[[1 2 3]
 [4 5 6]]
1250205327600
1250225914384


In [31]:
#adding values at the end of an array 
original_arr = [1,2,3,4,5]
append_arr = [6,7,8,9,10]   

final_arr = np.append(original_arr, append_arr)

print(final_arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
#swaping two columns in a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, [0, 2]] = arr[:, [2, 0]] # swap columns 0 and 2
print(arr)

#swaping two rows in a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[[0, 2], :] = arr[[2, 0], :] 
print(arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [34]:
#concatenating two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_concat = np.concatenate((arr1, arr2), axis=1)
print(arr_concat)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
#merging two arrays with stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_stack = np.stack((arr1, arr2), axis=1) #merge by columns
arr_stack_0= np.stack((arr1, arr2), axis=0) #merge by rows
print(arr_stack)
print(arr_stack_0)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
#define an array 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1][1], arr[1, 1]) # 5 5

5 5


In [4]:
#comparing two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(np.array_equal(arr1, arr2)) # True #array_equal method is used to compare two arrays for equality
print(np.array_equiv(arr1, arr2)) # True #array_equiv method is used to compare two arrays for equality within a tolerance
print(np.allclose(arr1, arr2)) # True #allclose method is used to compare two arrays element-wise within a tolerance

True
True
True


In [5]:
#comparing two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = arr1 == arr2
print(arr3) # [False False False]

print(np.greater(arr1, arr2)) # [False False False] #greater method is used to compare two arrays element-wise
print(np.greater_equal(arr1, arr2)) # [False False False] #greater_equal method is used to compare two arrays element-wise
print(np.less(arr1, arr2)) # [True True True] #less method is used to compare two arrays element-wise
print(np.less_equal(arr1, arr2)) # [True True True] #less_equal method is used to compare two arrays element-wise


[False False False]
[False False False]
[False False False]
[ True  True  True]
[ True  True  True]


In [8]:
#finding unique values in an array
arr = np.array([[1, 2, 3, 1, 2, 3, 4, 5], [1, 2, 2, 1, 2, 5, 4, 5], [1, 2, 6, 1, 6, 3, 4, 5]])
unique_values = np.unique(arr)
print(unique_values) # [1 2 3 4 5 6]
print(np.unique(arr, return_counts=True)) # (array([1, 2, 3, 4, 5, 6]), array([3, 3, 2, 2, 2, 2])) #return_counts parameter is used to return the number of times each unique value appears in the array
print(np.unique(arr, return_index=True)) # (array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 6, 7, 10])) #return_index parameter is used to return the indices of the unique values in the original array
print(np.unique(arr, axis=0)) #unique vectors in array in axis 0
print(np.unique(arr, axis=1)) #unique vectors in array in axis 1

[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([6, 6, 3, 3, 4, 2], dtype=int64))
(array([1, 2, 3, 4, 5, 6]), array([ 0,  1,  2,  6,  7, 18], dtype=int64))
[[1 2 2 1 2 5 4 5]
 [1 2 3 1 2 3 4 5]
 [1 2 6 1 6 3 4 5]]
[[1 2 2 3 3 4 5]
 [1 2 2 2 5 4 5]
 [1 2 6 6 3 4 5]]


In [9]:
#trim zeroes in the begining and ending in an array
arr = np.array([0,0,1,2,3,3,4.,0,0,6,4,0,0,])
new_arr = np.trim_zeros(arr)
print(new_arr)

[1. 2. 3. 3. 4. 0. 0. 6. 4.]


In [2]:
#bitwise in array
arr_1 = np.array([1,2,3,4,9,13])
arr_2 = np.array([1,2,6,20,14,25])

print("Bitwise And: ", np.bitwise_and(arr_1, arr_2))
print("Bitwise Or: ", np.bitwise_or(arr_1,arr_2))
print("Bitwise Xor: ", np.bitwise_xor(arr_1, arr_2))
print("Bitwise not: ", np.bitwise_not(arr_1, arr_2))
print("bitwise not(invert): ", np.invert(arr_1,arr_2))
print("left shit array with 2bits: ", np.left_shift(arr_1, 2))
print("right shift arr_1 with 2 bits: ", np.right_shift(arr_1,2))

Bitwise And:  [1 2 2 4 8 9]
Bitwise Or:  [ 1  2  7 20 15 29]
Bitwise Xor:  [ 0  0  5 16  7 20]
Bitwise not:  [ -2  -3  -4  -5 -10 -14]
bitwise not(invert):  [ -2  -3  -4  -5 -10 -14]
left shit array with 2bits:  [ 4  8 12 16 36 52]
right shift arr_1 with 2 bits:  [0 0 0 1 2 3]


In [7]:
#sinus and cosinus etc
signal_array = np.array([0.01, 0.1, 0.3, 0.45, 0.56, 0.87])
print("Sin of array: ", np.sin(signal_array))
print("Cos of array: ", np.cos(signal_array))
print("Tan of array: ", np.tan(signal_array))
print("Arcsin of array: ", np.arcsin(signal_array))
print("Arccos of array: ", np.arccos(signal_array))
print("Arctan of array: ", np.arctan(signal_array))
print("Change radian to degree of array: ", np.rad2deg(signal_array))
print("Change degree to radian of array: ", np.deg2rad(signal_array))

Sin of array:  [0.00999983 0.09983342 0.29552021 0.43496553 0.5311862  0.76432894]
Cos of array:  [0.99995    0.99500417 0.95533649 0.9004471  0.84725511 0.64482655]
Tan of array:  [0.01000033 0.10033467 0.30933625 0.48305507 0.62694954 1.18532486]
Arcsin of array:  [0.01000017 0.10016742 0.30469265 0.46676534 0.5943858  1.05520232]
Arccos of array:  [1.56079616 1.47062891 1.26610367 1.10403099 0.97641053 0.51559401]
Arctan of array:  [0.00999967 0.09966865 0.29145679 0.42285393 0.51048832 0.71599111]
Change radian to degree of array:  [ 0.5729578   5.72957795 17.18873385 25.78310078 32.08563653 49.84732818]
Change degree to radian of array:  [0.00017453 0.00174533 0.00523599 0.00785398 0.00977384 0.01518436]


In [8]:
print("Sinh of array: ", np.sinh(signal_array))
print("Cosh of array: ", np.cosh(signal_array))
print("Tanh of array: ", np.tanh(signal_array))
print("Arcsinh of array: ", np.arcsinh(signal_array))
print("Arccosh of array: ", np.arccosh(signal_array * 100)) # cosh is over 1 so we multiple signal_array *100
print("Arctanh of array: ", np.arctanh(signal_array))

Sinh of array:  [0.01000017 0.10016675 0.30452029 0.46534202 0.58973172 0.98397965]
Cosh of array:  [1.00005    1.00500417 1.04533851 1.10297017 1.16094078 1.4029312 ]
Tanh of array:  [0.00999967 0.09966799 0.29131261 0.42189901 0.50797743 0.70137413]
Arcsinh of array:  [0.00999983 0.09983408 0.29567305 0.43604967 0.53422407 0.78640118]
Arccosh of array:  [0.         2.99322285 4.09406667 4.49968619 4.71841914 5.15902227]
Arctanh of array:  [0.01000033 0.10033535 0.3095196  0.48470028 0.63283319 1.33307963]


In [ ]:
#linear algebra in numpy
a = np.array([[1, 2, 3], [4, 4, 6], [2, 5, 10]])
b = np.array([6, 7, 8])
arr_1 = [1, 2, 3, 4]
arr_2 = [1, 5, 3, 6]
print("Determinant: ", np.linalg.det(a)) #determinant of a matrix
print("Inverse: \n", np.linalg.inv(a)) #inverse of a matrix
print("Eigen values: \n", np.linalg.eigvals(a)) #eigen values of a matrix(eigen values are the values that scale the eigenvectors)
print("\nInner product of arr_1 and arr_2: ", np.dot(arr_1, arr_2)) #inner product of two arrays
print("\nInner product of arr_1 and arr_2: ", np.inner(arr_1, arr_2)) #inner product of two arrays
print("\nOuter product of arr_1 and arr_2: \n", np.outer(arr_1, arr_2)) #outer product of two arrays
print("\nResult of 'a * x = b' equation: ", np.linalg.solve(a, b)) #solve the equation 'a * x = b'
print("Norm of 'a' matrix: ", np.linalg.norm(a)) #norm of a matrix(norm is a function that returns the length of a vector)


Determinant:  -9.999999999999998
Inverse: 
 [[-1.   0.5  0. ]
 [ 2.8 -0.4 -0.6]
 [-1.2  0.1  0.4]]
Eigen values: 
 [14.24894017 -0.54252744  1.29358727]

Inner product of arr_1 and arr_2:  44

Inner product of arr_1 and arr_2:  44

Outer product of arr_1 and arr_2: 
 [[ 1  5  3  6]
 [ 2 10  6 12]
 [ 3 15  9 18]
 [ 4 20 12 24]]

Result of 'a * x = b' equation:  [-2.5  9.2 -3.3]
Norm of 'a' matrix:  14.52583904633395


In [10]:
#reshaping an array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("shape of array: ", array.shape)

print("new shape of array: \n", array.reshape(6, 2)) # convert 3*4 array to 6*2
print("\n2-d to 3-d conversion: \n", array.reshape(2, 2, 3)) # convert 2-d to 3-d 
print("\n1-d conversion of array: ", array.reshape(-1))

shape of array:  (3, 4)
new shape of array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

2-d to 3-d conversion: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1-d conversion of array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
#iterating in array(iterating means going through elements of an array)
my_array = np.array([1, 2, 3, 4, 5])
for i in my_array:
    print(i)

1
2
3
4
5


In [12]:
#iterating in 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6]])
#print elements
for i in my_array:
    for j in i:
        print(j) 

#print rows
for i in my_array:
    print(i)

1
2
3
4
5
6
[1 2 3]
[4 5 6]


In [13]:
#searching in an array
my_array = np.array([20, 15, 17, 18, 19, 18.5, 17.5, 16, 13, 12, 11])
val_list = np.where(my_array > 15) # elements that are bigger than 15
val_list_1 = np.where(my_array == 18) # elements that are equal to 18
print(val_list)
print(val_list_1)

(array([0, 2, 3, 4, 5, 6, 7], dtype=int64),)
(array([3], dtype=int64),)


In [14]:
#soring in array
my_array = np.array([2, 1, 8, 6, 3, 7, 4])
sorted_array = np.sort(my_array) # sort array
print(sorted_array, '\n')

my_array_1 = np.array([[3, 2, 1, 5], [6, 4, 5, 8]]) # sort 2-d array
print(np.sort(my_array_1))

[1 2 3 4 6 7 8] 

[[1 2 3 5]
 [4 5 6 8]]


In [16]:
#filtering arrays
my_array = np.array([10, 15, 16, 20, 18, 19])

# first solution
filter_ = [False, False, True, True, True, True]
filtered_array = my_array[filter_]
print(filtered_array)

# second solution
filter_ = []
for i in my_array:
    if (i > 15):
        filter_.append(True)
    else:
        filter_.append(False)

filtered_array = my_array[filter_]
print(filtered_array)

[16 20 18 19]
[16 20 18 19]
