In [2]:
import numpy as np

In [3]:
first_array = np.array(100) # 0-D array
print(first_array)

100


In [4]:
array_1d = np.array([1, 2, 3, 4, 5]) # 1-D array
print(array_1d)

[1 2 3 4 5]


In [5]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D array
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3-D array
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
#print dimension of every array
print(first_array.ndim)
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

0
1
2
3


In [8]:
#Higher Dimensional Arrays
array_5d = np.array([1, 2, 3, 4], ndmin=5)
print(array_5d)

[[[[[1 2 3 4]]]]]


In [11]:
#different methods to create arrays
#empty method
array_empty = np.empty((2, 3)) # 2x3 empty array
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#zero method
array_zeros = np.zeros((2, 3)) # 2x3 array with zeros
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#create an eye matrix(an eye matrix is a square matrix with 1's on the main diagonal)
array_eye = np.eye(3) # 3x3 identity matrix
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#create an ones matrix(ones matrix is a matrix where all the values are 1)
array_ones = np.ones((2, 3)) # 2x3 array with ones
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#create an array with arrange method between 1 and 2 by step 0.05
array_arrange = np.arange(1,2,0.05)
print(array_arrange)

[1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65
 1.7  1.75 1.8  1.85 1.9  1.95]


In [16]:
#an array with linspace method(linspace is used to create an array with a specified number of elements, and within a specified range)
array_linspace = np.linspace(1, 2, 10) # 10 elements between 1 and 2
print(array_linspace)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [19]:
#Meshgrid method(creates a rectangular grid out of an array of x values and an array of y values)
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

#creates a grid of x and y values
X, Y = np.meshgrid(x, y)

print(X)
print("\n")
print(Y)

[[-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 ...
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]]


[[-5.        -5.        -5.        ... -5.        -5.        -5.       ]
 [-4.8989899 -4.8989899 -4.8989899 ... -4.8989899 -4.8989899 -4.8989899]
 [-4.7979798 -4.7979798 -4.7979798 ... -4.7979798 -4.7979798 -4.7979798]
 ...
 [ 4.7979798  4.7979798  4.7979798 ...  4.7979798  4.7979798  4.7979798]
 [ 4.8989899  4.8989899  4.8989899 ...  4.8989899  4.8989899  4.8989899]
 [ 5.         5.         5.        ...  5.         5.         5.       ]]


In [20]:
#create a diagonal matrix(diagonal matrix is a square matrix that has values only in the main diagonal)
array_diag = np.diag([1, 2, 3, 4]) # diagonal matrix
print(array_diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
#create a diagonal matrix with offset(diagonal matrix with offset is a square matrix that has values only in the main diagonal and offset)
array_diag_offset = np.diag([1, 2, 3, 4], k=1) # diagonal matrix with offset
print(array_diag_offset)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [22]:
#create a random matrix
array_random = np.random.rand(2, 3) # 2x3 random matrix
print(array_random)

[[0.659832   0.38448408 0.45932392]
 [0.10665453 0.73941345 0.75761944]]


In [23]:
#create a random matrix with normal distribution(mean=0, std=1)(a normal distribution is a distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean)
array_random_normal = np.random.randn(2, 3) # 2x3 random matrix with normal distribution
print(array_random_normal)

[[ 0.31423825 -1.16831745 -0.58530079]
 [ 1.81750213  0.80054459 -0.00566925]]


In [24]:
#create a random matrix with integers
array_random_int = np.random.randint(1, 10, (2, 3)) # 2x3 random matrix with integers between 1 and 10
print(array_random_int)

[[3 7 7]
 [2 9 3]]


In [25]:
#converting a list into an array
list_exp  = [1,2,4,8,16]
np_arr = np.array(list_exp)

print(np_arr)
print(type(np_arr))

[ 1  2  4  8 16]
<class 'numpy.ndarray'>


In [26]:
#converting a tuple into an array
tuple_exp = (1,2,4,8,16)
np_arr = np.array(tuple_exp)

print(np_arr)
print(type(np_arr))

[ 1  2  4  8 16]
<class 'numpy.ndarray'>


In [28]:
#copying an array
array_copy = np.copy(array_2d) # copy array_2d
print(array_copy)

#show memory location of each array
print(id(array_2d))
print(id(array_copy))

[[1 2 3]
 [4 5 6]]
1250205327600
1250225787984


In [30]:
#copying an array with view method(view method is used to create a new array object that looks at the same data)
array_view = array_2d.view() # view array_2d
print(array_view)

#show memory location of each array
print(id(array_2d))
print(id(array_view))

[[1 2 3]
 [4 5 6]]
1250205327600
1250225914384


In [31]:
#adding values at the end of an array 
original_arr = [1,2,3,4,5]
append_arr = [6,7,8,9,10]   

final_arr = np.append(original_arr, append_arr)

print(final_arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
#swaping two columns in a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, [0, 2]] = arr[:, [2, 0]]
print(arr)

#swaping two rows in a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[[0, 2], :] = arr[[2, 0], :]
print(arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [34]:
#concatenating two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_concat = np.concatenate((arr1, arr2), axis=1)
print(arr_concat)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
#merging two arrays with stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_stack = np.stack((arr1, arr2), axis=1) #merge by columns
arr_stack_0= np.stack((arr1, arr2), axis=0) #merge by rows
print(arr_stack)
print(arr_stack_0)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
